### ISSUE TITLE
broken models.sql

### ISSUE THREAD

**Issue by cheluskin** [localprojects/Change-By-Us#10]
CREATE TABLE `project_need` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(10) DEFAULT NULL,
 <b> `subtype` varchar(10) DEFAULT NULL,</b>
  `request` varchar(64) DEFAULT NULL,
  `quantity` int(11) DEFAULT NULL,
  `description` text,
  `project_id` int(11) NOT NULL,
  `date` date DEFAULT NULL,
  `time` varchar(32) DEFAULT NULL,
  `duration` varchar(64) DEFAULT NULL,
  `address` varchar(256) DEFAULT NULL,
  `event_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `project_id` (`project_id`),
  KEY `event_id` (`event_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

need string <h1> `subtype` varchar(10) DEFAULT NULL,</h1>

**Comment by cybertoast** [comment]
cheluskin, The issue is handled by migration: giveaminute/migrations/versions/009_Add_a_sub-type_field_to_the_project_need_table.py.
The installation and setup process requires that all the migrations be run. Please let us know if there's still a problem with this or if I'm misunderstanding the issue.
